FROM alpine:3.18
RUN apk add --no-cache python3 py3-pip bash
RUN pip install paho-mqtt requests python_http_client protobuf grpcio-tools influxdb-client

WORKDIR /app
COPY ./src /app/src
COPY ./external /app/external
COPY protobuffer /app/protobuffer
RUN chmod +x ./protobuffer/compile.sh && ./protobuffer/compile.sh

MOUNT config.json /app/config.json

CMD ["python3", "-m", "src.index", "config.json"]
