name: influx-test-env
services:
    influxdb2:
        hostname: influxdb
        build:
            context: .
            dockerfile: Dockerfile.influx.yml
        ports:
            - "8086:8086"
        volumes:
            - type: volume
              source: influxdb2-data
              target: /var/lib/influxdb2
            - type: volume
              source: influxdb2-config
              target: /etc/influxdb2
        networks:
            - default
    mosquitto:
        hostname: mosquitto
        build:
            context: .
            dockerfile: Dockerfile.mosquitto.yml
        ports:
            - "8883:8883"
        networks:
            - default
    manager:
        build:
            context: .
            dockerfile: Dockerfile.manager.yml
        ports:
            - "8000:8000"
        depends_on:
            - influxdb2
            - mosquitto
        networks:
            - default
secrets:
    influxdb2-admin-username:
        file: ./.env.influxdb2-admin-username
    influxdb2-admin-password:
        file: ./.env.influxdb2-admin-password
    influxdb2-admin-token:
        file: ./.env.influxdb2-admin-token
volumes:
    influxdb2-data:
        driver: local
    influxdb2-config:
        driver: local
networks:
    default:
        driver: bridge
