FROM alpine:3.18
# Install Python 3 and pip
RUN apk add --no-cache python3 py3-pip python3-dev && \
    # cleanup
    rm -rf /var/cache/apk/*
# Install Python dependencies
RUN pip install --upgrade pip && \
    #install dependencies
    pip install paho-mqtt requests python_http_client protobuf grpcio-tools influxdb-client python-statemachine pydot && \
    # cleanup
    apk del --no-cache py3-pip python3-dev

WORKDIR /app
COPY ./src /app/src
# Bidirectionally mount cache directory to persist downloaded .proto files across container runs
#VOLUME /app/cache

CMD ["python3", "-m", "src.main", "config.json"]
