name: influx-test-env
services:
    influxdb2:
        build:
            context: .
            dockerfile: Dockerfile.influx.yml
        ports:
            - "8086:8086"
        volumes:
            - type: volume
              source: influxdb2-data
              target: /var/lib/influxdb2
            - type: volume
              source: influxdb2-config
              target: /etc/influxdb
    manager:
        build:
            context: .
            dockerfile: Dockerfile.manager.yml
        ports:
            - "8000:8000"
        depends_on:
            - influxdb2
secrets:
    influxdb2-admin-username:
        file: ./.env.influxdb2-admin-username
    influxdb2-admin-password:
        file: ./.env.influxdb2-admin-password
    influxdb2-admin-token:
        file: ./.env.influxdb2-admin-token
volumes:
    influxdb2-data:
        driver: local
    influxdb2-config:
        driver: local
