reporting-disabled = false
bind-address = ":8088"

[meta]
	dir = "/var/lib/influxdb/meta"

[data]
	dir = "/var/lib/influxdb/data"
	wal-dir = "/var/lib/influxdb/wal"
	index-version = "inmem"
	query-log-enabled = true
	trace-logging-enabled = false

[coordinator]
	write-timeout = "10s"
	max-concurrent-queries = 0
	query-timeout = "0s"
	log-queries-after = "0s"
	max-select-point = 0
	max-select-series = 0
	max-select-buckets = 0

[retention]
	enabled = true
	check-interval = "30m"

[shard-precreation]
	enabled = true
	check-interval = "10m"
	advance-period = "30m"

[monitor]
	store-enabled = true
	store-database = "_internal"
	store-interval = "10s"

[http]
	enabled = true
	bind-address = ":8086"
	auth-enabled = false
	log-enabled = true
	write-tracing = false
	pprof-enabled = false
	https-enabled = false
	max-row-limit = 0
	max-connection-limit = 0
	shared-secret = ""
	realm = "InfluxDB"
	unix-socket-enabled = false

[subscriber]
	enabled = true
	http-timeout = "30s"
	insecure-skip-verify = false
	ca-certs = ""
	write-concurrency = 40
	write-buffer-size = 1000

[[graphite]]
	enabled = false

[[collectd]]
	enabled = false

[[opentsdb]]
	enabled = false

[[udp]]
	enabled = true

[continuous_queries]
	enabled = true
	log-enabled = true
	run-interval = "1s"

[tls]
	min-version = "tls1.2"
	max-version = ""
