'''
Bridge between the influx-logger and the 'telemetry-serializers' submodule.

Importing this package makes the generated protobuf code importable:

  - '<repo>/.generated'            holds the '*_pb2.py' modules produced by protoc
                                   (see the 'proto' target of the Makefile)
  - '<repo>/external/serializer/py' holds the dataclass wrappers published by the
                                   CI on the 'dev-build' branch of telemetry-serializers

Both directories contribute to the same 'influxlogger' namespace package, so
'influxlogger.query' (wrapper) and 'influxlogger.query_pb2' (protobuf) resolve
even though they live in different trees.
'''
import sys

from pathlib import Path

REPO_ROOT: Path = Path(__file__).resolve().parents[2]
'''Root of the influx-logger repository, used to locate the generated code.'''

GENERATED_DIR: Path = REPO_ROOT / ".generated"
'''Directory holding the protobuf modules generated by protoc.'''

SERIALIZER_PY_DIR: Path = REPO_ROOT / "external" / "serializer" / "py"
'''Directory holding the dataclass wrappers shipped by the telemetry-serializers submodule.'''

for _path in (GENERATED_DIR, SERIALIZER_PY_DIR):
    _entry = str(_path)
    if _path.is_dir() and _entry not in sys.path:
        sys.path.insert(0, _entry)

__all__ = ["REPO_ROOT", "GENERATED_DIR", "SERIALIZER_PY_DIR"]
